{
 "title": "Infrastructure Overview",
 "tags": [
  "autoops",
  "infrastructure"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "monitoring status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{instance=\"localhost:9090\",job=\"prometheus\"})\r\n",
     "legendFormat": "prometheus"
    },
    {
     "expr": "max(up{instance=\"node-exporter:9100\",job=\"monitoring-node-exporter\"})",
     "legendFormat": "node-exporter"
    },
    {
     "expr": "max(up{instance=\"alertmanager:9093\",job=\"alertmanager\"})",
     "legendFormat": "altmanager"
    }
   ]
  },
  {
   "title": "App Nodes Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"app-node-exporter\"} / node_memory_MemTotal_bytes{job=\"app-node-exporter\"})) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app1 status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{instance=\"10.0.2.130:5000\",job=\"demo-app\"})",
     "legendFormat": "demo-app"
    },
    {
     "expr": "max(up{instance=\"10.0.2.130:8080\",job=\"app-cadvisor\"})",
     "legendFormat": "cadvisor"
    },
    {
     "expr": "max(up{instance=\"10.0.2.130:9100\",job=\"app-node-exporter\"})",
     "legendFormat": "node-exporter"
    }
   ]
  },
  {
   "title": "App Nodes CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"app-node-exporter\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "app2 status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{instance=\"10.0.2.118:5000\",job=\"demo-app\"})",
     "legendFormat": "demo-app"
    },
    {
     "expr": "max(up{instance=\"10.0.2.118:8080\",job=\"app-cadvisor\"})",
     "legendFormat": "cadvisor"
    },
    {
     "expr": "max(up{instance=\"10.0.2.118:9100\",job=\"app-node-exporter\"})",
     "legendFormat": "node-exporter"
    }
   ]
  }
 ]
}