[monitoring_nodes]
monitoring ansible_host=16.16.216.16

[app]
app1 ansible_host=10.0.2.130
app2 ansible_host=10.0.2.118

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=/home/markus/.ssh/autoops-dev-key.pem

[app:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/markus/.ssh/autoops-dev-key.pem -o IdentitiesOnly=yes -W %h:%p ec2-user@16.16.216.16"'